# Generated by Django 4.2 on 2023-04-26 12:55

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='recipe',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('recipe_name', models.CharField(max_length=200)),
                ('servings', models.IntegerField(default=1)),
                ('prep_time', models.IntegerField(default=10)),
                ('cook_time', models.IntegerField(default=0)),
                ('ingredient_list', models.CharField(max_length=500)),
                ('instructions', models.CharField(max_length=500)),
            ],
        ),
    ]
