# Generated by Django 4.2 on 2023-04-27 06:42

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('website', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='recipe',
            name='category',
            field=models.CharField(default='Entree', max_length=50),
        ),
    ]
